### PR TITLE
Added dev link change

### PR DESCRIPTION
**Pull request by gfportfolio**

### CODE REVIEW

**Review by visum — COMMENTED** [review]
Do bindings in the markup provide a way to do this same thing more declaratively?

**Comment by gfportfolio** [comment]
I am not sure how I might do this when the url can be different depending on the app.  For example producercodetool is different then manage

**Comment by aarondrabeck** [comment]
You can create a property called isDevelopment.  Then create a func for internal use 

_getDevelopmentPrefix(isDevelopment :boolean) : string { 
return isDevelopment ? 'dev' : '';
}

Now in html: 



`<a href="https://[[_getDevelopmentPrefix(isDevelopment)]]producertoolthingy.blabla.com/foo/bar" >.`

Then let the consumer deal with setting the is-development attribute as it's much too presumptive to do it in here.

**Review by aarondrabeck — CHANGES_REQUESTED** [review]
You can create a property called isDevelopment. Then create a func for internal use

```
_getDevelopmentPrefix(isDevelopment :boolean) : string {
return isDevelopment ? 'dev' : '';
}

```
Now in html:

`> <a href="https://[[_getDevelopmentPrefix(isDevelopment)]]producertoolthingy.blabla.com/foo/bar" >.
`

Then let the consumer deal with setting the is-development attribute as it's much too presumptive to do it in here.

**Pull request closed without merging**
